### ISSUE TITLE
ARM support for Linux?

### ISSUE THREAD

**Issue by cobalt2727** [Lojemiru/AM2R-Autopatcher-Linux#13]
Since the Android build already supports ARM, how hard would it be to set this up on an ARM Linux device? (Also, is 64-bit support feasible? Tegra hardware only has 64-bit graphics libraries...)

**Comment by Miepee** [comment]
This currently runs in 64-bit Linux machines, with "multilib" / "multiarch" enabled (basically, allows you to run 32-bit applications on a 64-bit system).
Regarding ARM linux support, I doubt that this will happen anytime soon, since GameMakers export options does not allow that.
The closest you could get, would be to install Android on your ARM machine.

**Comment by cobalt2727** [comment]
Wait, how does the Android version work then?

**Comment by Miepee** [comment]
Game Maker supports exporting to Android. It does not exporting to ARM Linux.

**Comment by cobalt2727** [comment]
Gotcha.

**Comment by cobalt2727** [comment]
https://gms.yoyogames.com/ReleaseNotes.html
It supports exporting to 32-bit Ubuntu ARM though, right?

**Comment by Miepee** [comment]
1. "32-bit ARM" does not exist.
2. That's for Game Maker Studio 2. This project uses Game Maker Studio 1.4
No, 1.4 projects are not compatible easily with Studio 2. And a rewrite to Studio 2, is not something that is going to happen anytime soon.

**Comment by cobalt2727** [comment]
Ah, thanks

**Comment by Lojemiru** [comment]
As Miepee has stated, this is unfortunately not feasible under our current development scheme. Thank you for the inquiry though!
