### ISSUE TITLE
Patcher script does not generate a valid APK

### ISSUE THREAD

**Issue by B-Nerd** [Lojemiru/AM2R-Autopatcher-Linux#26]
there is no am2r.ini in data/android
so i can't make a android apk if i use a older version of it there is no music the ini was in version 1.5.2 
but it is not there in version 1.5.4

**Comment by Miepee** [comment]
All command line  (e.g. Windows, Linux and I think Android as well) are currently broken. From 1.5.3 and onwards, the community updates started using the VM compilation method instead of YYC. Using the [AM2RLauncher](https://github.com/AM2R-Community-Developers/AM2RLauncher) right now is recommended.

For this issue specifically tho, VM builds don't need an .ini file. If you comment out [this](https://github.com/AM2R-Community-Developers/AM2R-Autopatcher-Linux/blob/190d93d1a7736ea9299349e2b278b3c494bb06c5/patcher.py#L243) line, you should be able to just create it fine.

**Comment by B-Nerd** [comment]
sadly the linux version of the AM2RLauncher does not work in linux  but i can run the autopatcher but it has  no music

**Comment by Miepee** [comment]
The AM2RLauncher has a native Linux version available, no need to run it via WINE.

**Comment by B-Nerd** [comment]
the problem the linux version does not work

**Comment by Miepee** [comment]
How so?

**Comment by B-Nerd** [comment]
just does not start

**Comment by Miepee** [comment]
1. Make sure you have all Dependencies installed (the release page details which ones you need)
2. Make sure the Launcher is marked as an executable (`chmod +x ./AM2RLauncher.Gtk`
3. Execute the Launcher (`./AM2RLauncher.Gtk`)

For further setup help, please visit the [AM2R Discord Server](https://discord.gg/YTQnkAJ).
